### ISSUE TITLE
Product Seeding Issue

### ISSUE THREAD

**Issue by jaredwastaken** [Agilo/fashion-starter#4]
When running yarn seed I am getting the following error. Postgres DB is running fine & I ran the migration before.
Rest of the seed script runs fine but it crashes @ products.

info:    Seeding product data...
error:   No value provided for input HTTP label: Bucket.
Error: No value provided for input HTTP label: Bucket.

**Comment by anteprimorac** [comment]
@jaredwastaken, thank you for reporting the issue. We have now added a local minio service for files. You can take a look into what we changed in this commit and apply it to your local env https://github.com/Agilo/fashion-starter/commit/7b4ccd38de8fece02beaaf596d868d297d030a5e.
